# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Talisman
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Talisman is a tool is to validate code changes that are to be pushed out of a
  local Git repository on a developer's workstation. By hooking into the
  pre-push hook provided by Git, it validates the outgoing changeset for things
  that look suspicious - such as potential SSH keys, authorization tokens,
  private keys etc. The aim is for Talisman to scan both file names and file
  content so that even potential problems embedded in source code and
  documentation can be caught.
baseurl: "/talisman" # the subpath of your site, e.g. /blog
url: "https://thoughtworks.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
